### ISSUE TITLE
Make Champollion compatible with Sphinx >= 1.8.0

### ISSUE THREAD

**Issue by rupalkhilari** [buddly27/champollion#1]
As noted in the [release notes for v0.8.1](https://champollion.readthedocs.io/en/stable/release_notes.html#release-0.8.1), Champollion is not compatible with Sphinx >= 1.8.0 due to the exclusion of the Directive class from Sphinx. 

It would be great if Champollion could be updated to also support Sphinx >= 1.8.0.

**Comment by buddly27** [comment]
It's about time, but v1.0.0 should fix the issue and add compatibility to latest Sphinx versions!
